//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoForm.ReservaReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/LocadoraVeiculosWCF")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cli_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_CodPlanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Res_DataReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Res_DataRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_DiariasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_HorasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Res_PcDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Res_PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Res_VlDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Res_VlTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cli_Codigo {
            get {
                return this.Cli_CodigoField;
            }
            set {
                if ((this.Cli_CodigoField.Equals(value) != true)) {
                    this.Cli_CodigoField = value;
                    this.RaisePropertyChanged("Cli_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_CodPlano {
            get {
                return this.Res_CodPlanoField;
            }
            set {
                if ((this.Res_CodPlanoField.Equals(value) != true)) {
                    this.Res_CodPlanoField = value;
                    this.RaisePropertyChanged("Res_CodPlano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_Codigo {
            get {
                return this.Res_CodigoField;
            }
            set {
                if ((this.Res_CodigoField.Equals(value) != true)) {
                    this.Res_CodigoField = value;
                    this.RaisePropertyChanged("Res_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Res_DataReserva {
            get {
                return this.Res_DataReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.Res_DataReservaField, value) != true)) {
                    this.Res_DataReservaField = value;
                    this.RaisePropertyChanged("Res_DataReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Res_DataRetorno {
            get {
                return this.Res_DataRetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.Res_DataRetornoField, value) != true)) {
                    this.Res_DataRetornoField = value;
                    this.RaisePropertyChanged("Res_DataRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_Diarias {
            get {
                return this.Res_DiariasField;
            }
            set {
                if ((this.Res_DiariasField.Equals(value) != true)) {
                    this.Res_DiariasField = value;
                    this.RaisePropertyChanged("Res_Diarias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_Horas {
            get {
                return this.Res_HorasField;
            }
            set {
                if ((this.Res_HorasField.Equals(value) != true)) {
                    this.Res_HorasField = value;
                    this.RaisePropertyChanged("Res_Horas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res_PcDesconto {
            get {
                return this.Res_PcDescontoField;
            }
            set {
                if ((this.Res_PcDescontoField.Equals(value) != true)) {
                    this.Res_PcDescontoField = value;
                    this.RaisePropertyChanged("Res_PcDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Res_Placa {
            get {
                return this.Res_PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.Res_PlacaField, value) != true)) {
                    this.Res_PlacaField = value;
                    this.RaisePropertyChanged("Res_Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res_VlDesconto {
            get {
                return this.Res_VlDescontoField;
            }
            set {
                if ((this.Res_VlDescontoField.Equals(value) != true)) {
                    this.Res_VlDescontoField = value;
                    this.RaisePropertyChanged("Res_VlDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res_VlTotal {
            get {
                return this.Res_VlTotalField;
            }
            set {
                if ((this.Res_VlTotalField.Equals(value) != true)) {
                    this.Res_VlTotalField = value;
                    this.RaisePropertyChanged("Res_VlTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Placa {
            get {
                return this.Vei_PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_PlacaField, value) != true)) {
                    this.Vei_PlacaField = value;
                    this.RaisePropertyChanged("Vei_Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservaReference.IReservaWCF")]
    public interface IReservaWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaWCF/InsereReserva", ReplyAction="http://tempuri.org/IReservaWCF/InsereReservaResponse")]
        void InsereReserva(AplicacaoForm.ReservaReference.Reserva reservaInsere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaWCF/InsereReserva", ReplyAction="http://tempuri.org/IReservaWCF/InsereReservaResponse")]
        System.Threading.Tasks.Task InsereReservaAsync(AplicacaoForm.ReservaReference.Reserva reservaInsere);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaWCFChannel : AplicacaoForm.ReservaReference.IReservaWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaWCFClient : System.ServiceModel.ClientBase<AplicacaoForm.ReservaReference.IReservaWCF>, AplicacaoForm.ReservaReference.IReservaWCF {
        
        public ReservaWCFClient() {
        }
        
        public ReservaWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsereReserva(AplicacaoForm.ReservaReference.Reserva reservaInsere) {
            base.Channel.InsereReserva(reservaInsere);
        }
        
        public System.Threading.Tasks.Task InsereReservaAsync(AplicacaoForm.ReservaReference.Reserva reservaInsere) {
            return base.Channel.InsereReservaAsync(reservaInsere);
        }
    }
}
