//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoForm.SFLocadora {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/LocadoraVeiculosWCF")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cli_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_CodPlanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Res_DataReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Res_DataRetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_DiariasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Res_HorasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Res_PcDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Res_PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Res_VlDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Res_VlTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_PlacaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cli_Codigo {
            get {
                return this.Cli_CodigoField;
            }
            set {
                if ((this.Cli_CodigoField.Equals(value) != true)) {
                    this.Cli_CodigoField = value;
                    this.RaisePropertyChanged("Cli_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_CodPlano {
            get {
                return this.Res_CodPlanoField;
            }
            set {
                if ((this.Res_CodPlanoField.Equals(value) != true)) {
                    this.Res_CodPlanoField = value;
                    this.RaisePropertyChanged("Res_CodPlano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_Codigo {
            get {
                return this.Res_CodigoField;
            }
            set {
                if ((this.Res_CodigoField.Equals(value) != true)) {
                    this.Res_CodigoField = value;
                    this.RaisePropertyChanged("Res_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Res_DataReserva {
            get {
                return this.Res_DataReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.Res_DataReservaField, value) != true)) {
                    this.Res_DataReservaField = value;
                    this.RaisePropertyChanged("Res_DataReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Res_DataRetorno {
            get {
                return this.Res_DataRetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.Res_DataRetornoField, value) != true)) {
                    this.Res_DataRetornoField = value;
                    this.RaisePropertyChanged("Res_DataRetorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_Diarias {
            get {
                return this.Res_DiariasField;
            }
            set {
                if ((this.Res_DiariasField.Equals(value) != true)) {
                    this.Res_DiariasField = value;
                    this.RaisePropertyChanged("Res_Diarias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Res_Horas {
            get {
                return this.Res_HorasField;
            }
            set {
                if ((this.Res_HorasField.Equals(value) != true)) {
                    this.Res_HorasField = value;
                    this.RaisePropertyChanged("Res_Horas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res_PcDesconto {
            get {
                return this.Res_PcDescontoField;
            }
            set {
                if ((this.Res_PcDescontoField.Equals(value) != true)) {
                    this.Res_PcDescontoField = value;
                    this.RaisePropertyChanged("Res_PcDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Res_Placa {
            get {
                return this.Res_PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.Res_PlacaField, value) != true)) {
                    this.Res_PlacaField = value;
                    this.RaisePropertyChanged("Res_Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res_VlDesconto {
            get {
                return this.Res_VlDescontoField;
            }
            set {
                if ((this.Res_VlDescontoField.Equals(value) != true)) {
                    this.Res_VlDescontoField = value;
                    this.RaisePropertyChanged("Res_VlDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Res_VlTotal {
            get {
                return this.Res_VlTotalField;
            }
            set {
                if ((this.Res_VlTotalField.Equals(value) != true)) {
                    this.Res_VlTotalField = value;
                    this.RaisePropertyChanged("Res_VlTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Placa {
            get {
                return this.Vei_PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_PlacaField, value) != true)) {
                    this.Vei_PlacaField = value;
                    this.RaisePropertyChanged("Vei_Placa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes", Namespace="http://schemas.datacontract.org/2004/07/LocadoraVeiculosWCF")]
    [System.SerializableAttribute()]
    public partial class Clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cli_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_DataHabilitacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_DatadeNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_EmissorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_ExpedicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_RegistroRenachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cli_ValidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Bairro {
            get {
                return this.Cli_BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_BairroField, value) != true)) {
                    this.Cli_BairroField = value;
                    this.RaisePropertyChanged("Cli_Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_CEP {
            get {
                return this.Cli_CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_CEPField, value) != true)) {
                    this.Cli_CEPField = value;
                    this.RaisePropertyChanged("Cli_CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_CPF {
            get {
                return this.Cli_CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_CPFField, value) != true)) {
                    this.Cli_CPFField = value;
                    this.RaisePropertyChanged("Cli_CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Categoria {
            get {
                return this.Cli_CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_CategoriaField, value) != true)) {
                    this.Cli_CategoriaField = value;
                    this.RaisePropertyChanged("Cli_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Cidade {
            get {
                return this.Cli_CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_CidadeField, value) != true)) {
                    this.Cli_CidadeField = value;
                    this.RaisePropertyChanged("Cli_Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cli_Codigo {
            get {
                return this.Cli_CodigoField;
            }
            set {
                if ((this.Cli_CodigoField.Equals(value) != true)) {
                    this.Cli_CodigoField = value;
                    this.RaisePropertyChanged("Cli_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_DataHabilitacao {
            get {
                return this.Cli_DataHabilitacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_DataHabilitacaoField, value) != true)) {
                    this.Cli_DataHabilitacaoField = value;
                    this.RaisePropertyChanged("Cli_DataHabilitacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_DatadeNascimento {
            get {
                return this.Cli_DatadeNascimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_DatadeNascimentoField, value) != true)) {
                    this.Cli_DatadeNascimentoField = value;
                    this.RaisePropertyChanged("Cli_DatadeNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Emissor {
            get {
                return this.Cli_EmissorField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_EmissorField, value) != true)) {
                    this.Cli_EmissorField = value;
                    this.RaisePropertyChanged("Cli_Emissor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Endereco {
            get {
                return this.Cli_EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_EnderecoField, value) != true)) {
                    this.Cli_EnderecoField = value;
                    this.RaisePropertyChanged("Cli_Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Expedicao {
            get {
                return this.Cli_ExpedicaoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_ExpedicaoField, value) != true)) {
                    this.Cli_ExpedicaoField = value;
                    this.RaisePropertyChanged("Cli_Expedicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Nome {
            get {
                return this.Cli_NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_NomeField, value) != true)) {
                    this.Cli_NomeField = value;
                    this.RaisePropertyChanged("Cli_Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_RG {
            get {
                return this.Cli_RGField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_RGField, value) != true)) {
                    this.Cli_RGField = value;
                    this.RaisePropertyChanged("Cli_RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_RegistroRenach {
            get {
                return this.Cli_RegistroRenachField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_RegistroRenachField, value) != true)) {
                    this.Cli_RegistroRenachField = value;
                    this.RaisePropertyChanged("Cli_RegistroRenach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Sexo {
            get {
                return this.Cli_SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_SexoField, value) != true)) {
                    this.Cli_SexoField = value;
                    this.RaisePropertyChanged("Cli_Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Telefone {
            get {
                return this.Cli_TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_TelefoneField, value) != true)) {
                    this.Cli_TelefoneField = value;
                    this.RaisePropertyChanged("Cli_Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_UF {
            get {
                return this.Cli_UFField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_UFField, value) != true)) {
                    this.Cli_UFField = value;
                    this.RaisePropertyChanged("Cli_UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cli_Validade {
            get {
                return this.Cli_ValidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cli_ValidadeField, value) != true)) {
                    this.Cli_ValidadeField = value;
                    this.RaisePropertyChanged("Cli_Validade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Veiculos", Namespace="http://schemas.datacontract.org/2004/07/LocadoraVeiculosWCF")]
    [System.SerializableAttribute()]
    public partial class Veiculos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_AirbagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_AnoFabricacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_AnoModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_ArCondicionadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_BancoCouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_CambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_ComputadordeBordoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_ConectividadeInternetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_CorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_FreiosABSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_MotorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_NavegadorGPSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_RodaLigaLeveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_TipoDirecaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_TravaEletricaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_UFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vei_VidroEletricoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Airbags {
            get {
                return this.Vei_AirbagsField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_AirbagsField, value) != true)) {
                    this.Vei_AirbagsField = value;
                    this.RaisePropertyChanged("Vei_Airbags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_AnoFabricacao {
            get {
                return this.Vei_AnoFabricacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_AnoFabricacaoField, value) != true)) {
                    this.Vei_AnoFabricacaoField = value;
                    this.RaisePropertyChanged("Vei_AnoFabricacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_AnoModelo {
            get {
                return this.Vei_AnoModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_AnoModeloField, value) != true)) {
                    this.Vei_AnoModeloField = value;
                    this.RaisePropertyChanged("Vei_AnoModelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_ArCondicionado {
            get {
                return this.Vei_ArCondicionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_ArCondicionadoField, value) != true)) {
                    this.Vei_ArCondicionadoField = value;
                    this.RaisePropertyChanged("Vei_ArCondicionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_BancoCouro {
            get {
                return this.Vei_BancoCouroField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_BancoCouroField, value) != true)) {
                    this.Vei_BancoCouroField = value;
                    this.RaisePropertyChanged("Vei_BancoCouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Cambio {
            get {
                return this.Vei_CambioField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_CambioField, value) != true)) {
                    this.Vei_CambioField = value;
                    this.RaisePropertyChanged("Vei_Cambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Categoria {
            get {
                return this.Vei_CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_CategoriaField, value) != true)) {
                    this.Vei_CategoriaField = value;
                    this.RaisePropertyChanged("Vei_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_ComputadordeBordo {
            get {
                return this.Vei_ComputadordeBordoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_ComputadordeBordoField, value) != true)) {
                    this.Vei_ComputadordeBordoField = value;
                    this.RaisePropertyChanged("Vei_ComputadordeBordo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_ConectividadeInternet {
            get {
                return this.Vei_ConectividadeInternetField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_ConectividadeInternetField, value) != true)) {
                    this.Vei_ConectividadeInternetField = value;
                    this.RaisePropertyChanged("Vei_ConectividadeInternet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Cor {
            get {
                return this.Vei_CorField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_CorField, value) != true)) {
                    this.Vei_CorField = value;
                    this.RaisePropertyChanged("Vei_Cor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Descricao {
            get {
                return this.Vei_DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_DescricaoField, value) != true)) {
                    this.Vei_DescricaoField = value;
                    this.RaisePropertyChanged("Vei_Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_FreiosABS {
            get {
                return this.Vei_FreiosABSField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_FreiosABSField, value) != true)) {
                    this.Vei_FreiosABSField = value;
                    this.RaisePropertyChanged("Vei_FreiosABS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Marca {
            get {
                return this.Vei_MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_MarcaField, value) != true)) {
                    this.Vei_MarcaField = value;
                    this.RaisePropertyChanged("Vei_Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Modelo {
            get {
                return this.Vei_ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_ModeloField, value) != true)) {
                    this.Vei_ModeloField = value;
                    this.RaisePropertyChanged("Vei_Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Motor {
            get {
                return this.Vei_MotorField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_MotorField, value) != true)) {
                    this.Vei_MotorField = value;
                    this.RaisePropertyChanged("Vei_Motor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_NavegadorGPS {
            get {
                return this.Vei_NavegadorGPSField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_NavegadorGPSField, value) != true)) {
                    this.Vei_NavegadorGPSField = value;
                    this.RaisePropertyChanged("Vei_NavegadorGPS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_Placa {
            get {
                return this.Vei_PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_PlacaField, value) != true)) {
                    this.Vei_PlacaField = value;
                    this.RaisePropertyChanged("Vei_Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_RodaLigaLeve {
            get {
                return this.Vei_RodaLigaLeveField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_RodaLigaLeveField, value) != true)) {
                    this.Vei_RodaLigaLeveField = value;
                    this.RaisePropertyChanged("Vei_RodaLigaLeve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_TipoDirecao {
            get {
                return this.Vei_TipoDirecaoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_TipoDirecaoField, value) != true)) {
                    this.Vei_TipoDirecaoField = value;
                    this.RaisePropertyChanged("Vei_TipoDirecao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_TravaEletrica {
            get {
                return this.Vei_TravaEletricaField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_TravaEletricaField, value) != true)) {
                    this.Vei_TravaEletricaField = value;
                    this.RaisePropertyChanged("Vei_TravaEletrica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_UF {
            get {
                return this.Vei_UFField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_UFField, value) != true)) {
                    this.Vei_UFField = value;
                    this.RaisePropertyChanged("Vei_UF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vei_VidroEletrico {
            get {
                return this.Vei_VidroEletricoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vei_VidroEletricoField, value) != true)) {
                    this.Vei_VidroEletricoField = value;
                    this.RaisePropertyChanged("Vei_VidroEletrico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFLocadora.ILocadoraWCF")]
    public interface ILocadoraWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/InsereReserva", ReplyAction="http://tempuri.org/ILocadoraWCF/InsereReservaResponse")]
        void InsereReserva(AplicacaoForm.SFLocadora.Reserva reservaInsere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/InsereReserva", ReplyAction="http://tempuri.org/ILocadoraWCF/InsereReservaResponse")]
        System.Threading.Tasks.Task InsereReservaAsync(AplicacaoForm.SFLocadora.Reserva reservaInsere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/PesquisarCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/PesquisarClienteResponse")]
        AplicacaoForm.SFLocadora.Clientes PesquisarCliente(string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/PesquisarCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/PesquisarClienteResponse")]
        System.Threading.Tasks.Task<AplicacaoForm.SFLocadora.Clientes> PesquisarClienteAsync(string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/ListarCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/ListarClienteResponse")]
        System.Data.DataTable ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/ListarCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/ListarClienteResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/InsereCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/InsereClienteResponse")]
        void InsereCliente(AplicacaoForm.SFLocadora.Clientes cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/InsereCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/InsereClienteResponse")]
        System.Threading.Tasks.Task InsereClienteAsync(AplicacaoForm.SFLocadora.Clientes cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/AlteraCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/AlteraClienteResponse")]
        void AlteraCliente(AplicacaoForm.SFLocadora.Clientes cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/AlteraCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/AlteraClienteResponse")]
        System.Threading.Tasks.Task AlteraClienteAsync(AplicacaoForm.SFLocadora.Clientes cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/ExcluiCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/ExcluiClienteResponse")]
        void ExcluiCliente(AplicacaoForm.SFLocadora.Clientes cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/ExcluiCliente", ReplyAction="http://tempuri.org/ILocadoraWCF/ExcluiClienteResponse")]
        System.Threading.Tasks.Task ExcluiClienteAsync(AplicacaoForm.SFLocadora.Clientes cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/PesquisarVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/PesquisarVeiculoResponse")]
        AplicacaoForm.SFLocadora.Veiculos PesquisarVeiculo(string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/PesquisarVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/PesquisarVeiculoResponse")]
        System.Threading.Tasks.Task<AplicacaoForm.SFLocadora.Veiculos> PesquisarVeiculoAsync(string pesquisa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/InsereVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/InsereVeiculoResponse")]
        void InsereVeiculo(AplicacaoForm.SFLocadora.Veiculos veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/InsereVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/InsereVeiculoResponse")]
        System.Threading.Tasks.Task InsereVeiculoAsync(AplicacaoForm.SFLocadora.Veiculos veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/AlteraVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/AlteraVeiculoResponse")]
        void AlteraVeiculo(AplicacaoForm.SFLocadora.Veiculos veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/AlteraVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/AlteraVeiculoResponse")]
        System.Threading.Tasks.Task AlteraVeiculoAsync(AplicacaoForm.SFLocadora.Veiculos veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/ExcluiVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/ExcluiVeiculoResponse")]
        void ExcluiVeiculo(AplicacaoForm.SFLocadora.Veiculos veiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocadoraWCF/ExcluiVeiculo", ReplyAction="http://tempuri.org/ILocadoraWCF/ExcluiVeiculoResponse")]
        System.Threading.Tasks.Task ExcluiVeiculoAsync(AplicacaoForm.SFLocadora.Veiculos veiculo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocadoraWCFChannel : AplicacaoForm.SFLocadora.ILocadoraWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocadoraWCFClient : System.ServiceModel.ClientBase<AplicacaoForm.SFLocadora.ILocadoraWCF>, AplicacaoForm.SFLocadora.ILocadoraWCF {
        
        public LocadoraWCFClient() {
        }
        
        public LocadoraWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocadoraWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocadoraWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocadoraWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsereReserva(AplicacaoForm.SFLocadora.Reserva reservaInsere) {
            base.Channel.InsereReserva(reservaInsere);
        }
        
        public System.Threading.Tasks.Task InsereReservaAsync(AplicacaoForm.SFLocadora.Reserva reservaInsere) {
            return base.Channel.InsereReservaAsync(reservaInsere);
        }
        
        public AplicacaoForm.SFLocadora.Clientes PesquisarCliente(string pesquisa) {
            return base.Channel.PesquisarCliente(pesquisa);
        }
        
        public System.Threading.Tasks.Task<AplicacaoForm.SFLocadora.Clientes> PesquisarClienteAsync(string pesquisa) {
            return base.Channel.PesquisarClienteAsync(pesquisa);
        }
        
        public System.Data.DataTable ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
        
        public void InsereCliente(AplicacaoForm.SFLocadora.Clientes cliente) {
            base.Channel.InsereCliente(cliente);
        }
        
        public System.Threading.Tasks.Task InsereClienteAsync(AplicacaoForm.SFLocadora.Clientes cliente) {
            return base.Channel.InsereClienteAsync(cliente);
        }
        
        public void AlteraCliente(AplicacaoForm.SFLocadora.Clientes cliente) {
            base.Channel.AlteraCliente(cliente);
        }
        
        public System.Threading.Tasks.Task AlteraClienteAsync(AplicacaoForm.SFLocadora.Clientes cliente) {
            return base.Channel.AlteraClienteAsync(cliente);
        }
        
        public void ExcluiCliente(AplicacaoForm.SFLocadora.Clientes cliente) {
            base.Channel.ExcluiCliente(cliente);
        }
        
        public System.Threading.Tasks.Task ExcluiClienteAsync(AplicacaoForm.SFLocadora.Clientes cliente) {
            return base.Channel.ExcluiClienteAsync(cliente);
        }
        
        public AplicacaoForm.SFLocadora.Veiculos PesquisarVeiculo(string pesquisa) {
            return base.Channel.PesquisarVeiculo(pesquisa);
        }
        
        public System.Threading.Tasks.Task<AplicacaoForm.SFLocadora.Veiculos> PesquisarVeiculoAsync(string pesquisa) {
            return base.Channel.PesquisarVeiculoAsync(pesquisa);
        }
        
        public void InsereVeiculo(AplicacaoForm.SFLocadora.Veiculos veiculo) {
            base.Channel.InsereVeiculo(veiculo);
        }
        
        public System.Threading.Tasks.Task InsereVeiculoAsync(AplicacaoForm.SFLocadora.Veiculos veiculo) {
            return base.Channel.InsereVeiculoAsync(veiculo);
        }
        
        public void AlteraVeiculo(AplicacaoForm.SFLocadora.Veiculos veiculo) {
            base.Channel.AlteraVeiculo(veiculo);
        }
        
        public System.Threading.Tasks.Task AlteraVeiculoAsync(AplicacaoForm.SFLocadora.Veiculos veiculo) {
            return base.Channel.AlteraVeiculoAsync(veiculo);
        }
        
        public void ExcluiVeiculo(AplicacaoForm.SFLocadora.Veiculos veiculo) {
            base.Channel.ExcluiVeiculo(veiculo);
        }
        
        public System.Threading.Tasks.Task ExcluiVeiculoAsync(AplicacaoForm.SFLocadora.Veiculos veiculo) {
            return base.Channel.ExcluiVeiculoAsync(veiculo);
        }
    }
}
